CREATE TABLE nwimessages(
id BIGSERIAL NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email VARCHAR(250) NOT NULL,
subject VARCHAR(250) NOT NULL,
message VARCHAR(400) NOT NULL,
time VARCHAR(200) NOT NULL);
